name: CI/CD Pipeline

on:
  push:
    branches: [main]
    paths:
      - "public/**"
      - "**.yml"
      - "**.js"

jobs:
  prod-build:
    name: Build for Production
    if: ${{ github.ref == 'refs/heads/main' }}
    uses: ./.github/workflows/build.yml

  prod-deploy:
    name: Deploy to Production
    needs: prod-build
    if: ${{ needs.prod-build.result == 'success' }}
    uses: ./.github/workflows/deploy.yml
    secrets:
      SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
